# Site settings
title: José Hisse
description: > # this means to ignore newlines until "baseurl:"
  Engenheiro de dados (Big Data). Spark, Nifi, ElasticSearch,
  Kafka, Docker, BigQuery, Data lake
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://josehisse.dev' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - docker-compose.yml

permalink: pretty