# Site settings
title: Artigos sobre tecnologia escritos por José Hisse
description: > # this means to ignore newlines until "baseurl:"
  Engenheiro de dados (Big Data). Spark, Nifi, ElasticSearch,
  Kafka, Docker, BigQuery, Data lake
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://www.josehisse.dev' # the base hostname & protocol for your site

future: true

# Build settings
markdown: kramdown

exclude:
  - docker-compose.yml

include:
  - _redirects

permalink: /blog/:slug

kramdown:
  syntax_highlighter_opts:
    disable : true