name: Markdown Lint

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lintMarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: '.markdownlint.json'
          globs: 'content/**/*.md'
