name: Markdown Lint

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lintMarkdown:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          config: '.markdownlint.json'
          globs: 'content/**/*.md'
